In [2]:
# import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# available dataframes
actions = pd.read_csv("/data/container/actions.csv")
locations = pd.read_csv("/data/container/containerlocationinformation.csv")
handling = pd.read_csv("/data/container/handling.csv", low_memory=False) # dtype of 4 columns is unknown
machines = pd.read_csv("/data/container/machine.csv")
markers = pd.read_csv("/data/container/marker.csv")
entries = pd.read_csv("/data/container/stackentry.csv")
stacks = pd.read_csv("/data/container/stacks.csv")

display(handling.head(20))
print(handling.info())

,stopoveraction_id,endlocation,id,ended,planneddate,remark,startlocation,referenceaction_id,location_id,pos,...,connectedreason,connectedassigntosameexecutor,loadedwagonposition_id,hasalternatives,jobsposition,fromcontainerlocation_id,tocontainerlocation_id,shunt_id,missingagreement,reverts_id
0,3079280,NaN,3079277,NaN,NaN,NaN,NaN,3079278,738495,0.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
1,3187544,NaN,3187541,NaN,NaN,NaN,NaN,3187542,738495,0.0,...,NaN,False,NaN,False,163165176759087541,NaN,3187583.0,NaN,True,NaN
2,4021400,NaN,4021397,NaN,NaN,NaN,NaN,4021398,738495,0.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
3,3189746,NaN,3189743,NaN,NaN,NaN,NaN,3189744,738495,0.0,...,NaN,False,NaN,False,0,NaN,3189777.0,NaN,True,NaN
4,4021400,NaN,4021404,NaN,NaN,NaN,NaN,4021402,738495,1.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
5,3562878,NaN,6595778,2021-09-24 12:58:58.886907,NaN,NaN,NaN,3562878,738495,4.0,...,NaN,False,NaN,False,163248833192400000,4757324.0,6595856.0,NaN,True,NaN
6,9350432,NaN,10719664,2021-10-02 09:45:32.711894,NaN,NaN,NaN,9350432,738495,3.0,...,NaN,False,NaN,False,163316792520500000,9488388.0,10719682.0,NaN,True,NaN
7,3111970,NaN,3693255,2021-09-17 19:59:00.476511,NaN,NaN,NaN,3111970,738495,11.0,...,UNKNOWN,False,NaN,False,163181839945000000,3644120.0,NaN,NaN,False,NaN
8,3187432,NaN,3187429,NaN,NaN,NaN,NaN,3187430,738495,0.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
9,12257842,NaN,12332776,2021-10-06 14:43:28.935618,NaN,NaN,NaN,12257842,738495,-1.0,...,TWO_STEP_LOAD,False,NaN,False,163353115443532776,12334353.0,12334706.0,NaN,False,NaN
10,4022126,NaN,4022123,NaN,NaN,NaN,NaN,4022124,738495,0.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
11,3102919,NaN,4134770,2021-09-18 09:48:24.121091,NaN,NaN,NaN,3102919,738495,3.0,...,NaN,False,NaN,False,163195848990100000,NaN,4134803.0,NaN,True,NaN
12,3098975,NaN,3098967,2021-09-17 19:59:00.476511,NaN,NaN,NaN,3098969,738495,0.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
13,3189344,NaN,3189341,NaN,NaN,NaN,NaN,3189342,738495,0.0,...,NaN,False,NaN,False,0,NaN,3189353.0,NaN,True,NaN
14,4022126,NaN,4022130,NaN,NaN,NaN,NaN,4022128,738495,1.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
15,4022889,NaN,4022886,NaN,NaN,NaN,NaN,4022887,738495,0.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
16,3130303,NaN,3130299,2021-09-17 19:59:00.476511,NaN,NaN,NaN,3130300,738495,0.0,...,NaN,False,NaN,False,163188663977030299,NaN,3941974.0,NaN,True,NaN
17,4022889,NaN,4022893,NaN,NaN,NaN,NaN,4022891,738495,1.0,...,NaN,False,NaN,False,0,NaN,NaN,NaN,True,NaN
18,3121001,NaN,3120998,2021-09-17 19:59:00.476511,NaN,NaN,NaN,3120999,738495,0.0,...,NaN,False,NaN,False,163223515447820998,NaN,NaN,NaN,True,NaN
19,3280640,NaN,5812878,2021-09-23 08:33:31.288915,NaN,NaN,NaN,3280640,738495,4.0,...,NaN,False,NaN,False,163238574830900000,4147403.0,5815861.0,NaN,True,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42493 entries, 0 to 42492
Data columns (total 37 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   stopoveraction_id              42493 non-null  int64
 1   endlocation                    0 non-null      float64
 2   id                             42493 non-null  int64
 3   ended                          26685 non-null  object
 4   planneddate                    1 non-null      object
 5   remark                         289 non-null    object
 6   startlocation                  0 non-null      float64
 7   referenceaction_id             42493 non-null  int64
 8   location_id                    42493 non-null  int64
 9   pos                            42243 non-null  float64
 10  visible                        42493 non-null  bool
 11  priority                       42493 non-null  object
 12  started                        26698 non-null  object
 13  performer_id                   21426 non-null  float64
 14  handlingcategory               42493 non-null  object
 15  handlingtype                   42493 non-null  object
 16  handlingmethod                 42493 non-null  object
 17  deletedon                      9993 non-null   object
 18  autogenerated                  42493 non-null  bool
 19  debtor_id                      0 non-null      float64
 20  machine_id                     23240 non-null  float64
 21  promotiondate                  31025 non-null  object
 22  startrelativemarkerposition    0 non-null      float64
 23  endrelativemarkerposition      0 non-null      float64
 24  wagon_index                    0 non-null      float64
 25  connectedautoprioritize        42493 non-null  bool
 26  connectedbubble                42493 non-null  bool
 27  connectedreason                7124 non-null   object
 28  connectedassigntosameexecutor  42493 non-null  bool
 29  loadedwagonposition_id         0 non-null      float64
 30  hasalternatives                42493 non-null  bool
 31  jobsposition                   42493 non-null  int64
 32  fromcontainerlocation_id       27421 non-null  float64
 33  tocontainerlocation_id         27028 non-null  float64
 34  shunt_id                       0 non-null      float64
 35  missingagreement               42493 non-null  bool
 36  reverts_id                     234 non-null    float64
dtypes: bool(7), float64(14), int64(5), object(11)
memory usage: 10.0+ MB
None

In [3]:
readme = open("/data/container/readme.txt")
[print(line) for line in readme]
readme.close()

 == Markers + Stacks ==

Define the layout of the yard. All lengths and positions are defined in milimeters for a marker and a stack.

A stack is a specific block on the terminal, and a marker is a place within that stack you can position a container.



Based upon this information we can draw a mark for the yard.



 == Stack entry ==

This is a container placed in a specific stack. A stack entry is placed by a stackcorrection or handling.

A stack correction is a hard mutation done by someone in the backoffice. A handling is an actual activity done by a crane / stacker / carrier.

All stack entries with a put_mutation and without a pull mutation are currently in the yard.



 == handling ==

Alle movements of containers executed.



 == container location information ==

Shows a bit more information about where a container was or went to. A handling has a from and a to containerlocation information.



 == actions ==

Give information about the container which is transported.